### ISSUE TITLE
Option for exporting deployment annotations.

### ISSUE THREAD

**Issue by sch1ldkr0ete** [utilitywarehouse/kube-namespace-annotations-exporter#9]
Thanks for the good work! Missing this feature in the kube-state-metrics. Do you have any plans to include deployment annotations? Happy to support/contribute.

**Comment by george-angel** [comment]
Hello @Schildkroete23, thanks for the issue, very sorry we ignored it. I didn't have notifications enabled for this repository.

We will be archiving this project shortly, upstream now allows you to export labels and annotations in v0.2.2: https://github.com/kubernetes/kube-state-metrics/pull/1468
